---
title: "IBM Den: Figure 4" 
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    highlight: kate
    code_folding: true 
    toc: true            
    toc_depth: 2         
editor_options: 
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, 
                      retina = 1, dev = "ragg_png")
```


# Setup

```{r packages}
library(tidyverse)
library(ggtext)
library(patchwork)
library(systemfonts)
```


# Data

```{r data-prep}
results_all <- 
  readr::read_csv(
    here::here("data", "YBC_Continuous_Breeding single_run continuous_breeding-table.csv"), 
    skip = 6
  ) %>% 
  janitor::clean_names() %>% 
  mutate(type = if_else(immunity_barrier == 1, "baseline", "YBC")) %>% 
  rename(
    infecad = "count_hyenas_with_disease_infected_and_age_age_repro",
    infecjuv = "count_hyenas_with_disease_infected_and_age_age_repro_2",
    recovad = "count_hyenas_with_disease_recovered_and_age_age_repro",
    recovjuv = "count_hyenas_with_disease_recovered_and_age_age_repro_2",
    susad = "count_hyenas_with_disease_susceptible_and_age_age_repro",
    susjuv = "count_hyenas_with_disease_susceptible_and_age_age_repro_2"
  ) %>% 
  dplyr::select(step, type, abundance, susjuv, susad, infecjuv, infecad, recovjuv, recovad) %>% 
  pivot_longer(
    cols = susjuv:recovad,
    names_to = "group",
    values_to = "inds"
  ) %>% 
  mutate(SIR = case_when(
    str_detect(group, "sus") ~ "S",
    str_detect(group, "infec") ~ "I",
    str_detect(group, "recov") ~ "R"
  )) %>% 
  filter(step > 0)
```


# Figure

```{r plot, fig.width=16, fig.height=11}
theme_lucile <-
  theme_classic(base_size = 18, base_family = "Times New Roman") +
  theme(axis.title.x = element_text(margin = margin(t = 15)),
        axis.title.y = element_markdown(hjust = .4, margin = margin(r = 15)),
        axis.line = element_line(colour = 'black', size = .8),
        axis.ticks = element_line(size = .8), 
        axis.ticks.length = unit(0.2, "cm"),
        plot.title = element_text(hjust = .5, face = "bold"),
        legend.position = "none")


## Susceptible
lab <-
  results_all %>% 
  filter(SIR == "S", type == "YBC") %>%  
  filter((group == "susad" & step == 295) |  (group == "susjuv" & step == 160)) %>% 
  mutate(
    inds = if_else(group == "susjuv", inds + 27, inds - 20),
    label = if_else(group == "susjuv", "Juveniles", "Adults"),
    label_x = step + 35,
    label_y = if_else(group == "susjuv", inds + 190, inds - 170)
  )


#### COMMUNAL NURSERY ----------------------------------------------------------
## Susceptible
plot_a_proto <- 
  results_all %>% 
  filter(SIR == "S", type == "YBC") %>% 
  ggplot(aes(step, inds)) +
    geom_line(
      aes(
        color = group, 
        linetype = group
      ),
      size = 1.2
    ) +
    geom_segment(
      data = lab,
      aes(
        x = step,
        xend = label_x + 1,
        y = inds,
        yend = label_y,
        color = group
      ),
      size = .8
    ) +
    scale_x_continuous(
      expand = c(.015, .015),
      breaks = seq(0, 520, by = 52)
    ) +
    scale_y_continuous(
      expand = c(.03, .03),
      limits = c(0, 850), 
      breaks = seq(0, 800, by = 200)
    ) +
    scale_color_manual(values = c(colorspace::darken("#0090f7", .4), "#0090f7")) +
    scale_fill_manual(values = c(colorspace::darken("#0090f7", .4), "#0090f7")) +
    scale_linetype_manual(values = c("solid", 32)) +
    theme_lucile +
    labs(
      x = "Time (weeks)", 
      y = "&#35; of susceptibles&nbsp;&nbsp;*S*", 
      tag = expression(paste("(", italic("a"), ")"))
    )

plot_a <- 
  plot_a_proto +
  geom_label(
    data = lab,
    aes(
      label_x, label_y, 
      label = label,
      fill = group
    ),
    family = "Times New Roman",
    fontface = "bold",
    color = "white",
    size = 6.5,
    hjust = 0,
    label.r = unit(.6, "lines"),
    label.padding = unit(7.5, "pt"),
    label.size = 0
  ) 

## Infected
plot_b <- 
  results_all %>% 
  filter(SIR == "I", type == "YBC") %>% 
  ggplot(
    aes(
      step, inds, 
      color = group, 
      linetype = group
    )
  ) +
  geom_line(size = 1.2) +
  scale_x_continuous(
    expand = c(.015, .015),
    breaks = seq(0, 520, by = 52)
  ) +
  scale_y_continuous(
    expand = c(.03, .03),
    limits = c(0, 420), 
    breaks = seq(0, 400, by = 100)
  ) +
  scale_color_manual(values = c(colorspace::darken("#f20000", .4), "#f20000")) +
  scale_linetype_manual(values = c("solid", 32)) +
  theme_lucile +
  labs(
    x = "Time (weeks)", 
    y = "&#35; of infected&nbsp;&nbsp;*I*", 
    tag = expression(paste("(", italic("b"), ")"))
  )

## Recovered
plot_c <- 
  results_all %>% 
  filter(SIR == "R", type == "YBC") %>% 
  ggplot(
    aes(
      step, inds, 
      color = group, 
      linetype = group
    )
  ) +
  geom_line(size = 1.2) +
  scale_x_continuous(
    expand = c(.015, .015),
    breaks = seq(0, 520, by = 52)
  ) +
  scale_y_continuous(
    expand = c(.03, .03),
    limits = c(0, 850), 
    breaks = seq(0, 800, by = 200)
  ) +
  scale_color_manual(values = c(colorspace::darken("#00de6f", .4), "#00de6f")) +
  scale_linetype_manual(values = c("solid", 32)) +
  theme_lucile +
  labs(
    x = "Time (weeks)", 
    y = "&#35; of recovered&nbsp;&nbsp;*R*",
    tag = expression(paste("(", italic("c"), ")"))
  )


#### BASELINE SCENARIO ----------------------------------------------------------
## Susceptible
plot_d <-
  results_all %>% 
  filter(SIR == "S", type == "baseline") %>% 
  ggplot(
    aes(
      step, inds, 
      color = group, 
      linetype = group
      )
    ) +
    geom_line(size = 1.2) +
    scale_x_continuous(
      expand = c(.015, .015),
      breaks = seq(0, 520, by = 52)
    ) +
    scale_y_continuous(
      expand = c(.03, .03),
      limits = c(0, 850), 
      breaks = seq(0, 800, by = 200)
    ) +
    scale_color_manual(values = c(colorspace::darken("#0090f7", .4), "#0090f7")) +
    scale_linetype_manual(values = c("solid", 32)) +
    theme_lucile +
    labs(
      x = "Time (weeks)", 
      y = "&#35; of susceptibles&nbsp;&nbsp;*S*", 
      tag = expression(paste("(", italic("d"), ")"))
    )

## Infected
plot_e <-
  results_all %>% 
  filter(SIR == "I", type == "baseline") %>% 
  ggplot(
    aes(
      step, inds, 
      color = group, 
      linetype = group
    )
  ) +
  geom_line(size = 1.2) +
  scale_x_continuous(
    expand = c(.015, .015),
    breaks = seq(0, 520, by = 52)
  ) +
  scale_y_continuous(
    expand = c(.03, .03),
    limits = c(0, 420), 
    breaks = seq(0, 400, by = 100)
  ) +
  scale_color_manual(values = c(colorspace::darken("#f20000", .4), "#f20000")) +
  scale_linetype_manual(values = c("solid", 32)) +
  theme_lucile +
  labs(
    x = "Time (weeks)", 
    y = "&#35; of infected&nbsp;&nbsp;*I*", 
    tag = expression(paste("(", italic("e"), ")"))
  )

## Recovered
plot_f <-
  results_all %>% 
  filter(SIR == "R", type == "baseline") %>% 
  ggplot(
    aes(
      step, inds, 
      color = group, 
      linetype = group
    )
  ) +
  geom_line(size = 1.2) +
  scale_x_continuous(
    expand = c(.015, .015),
    breaks = seq(0, 520, by = 52)
  ) +
  scale_y_continuous(
    expand = c(.03, .03),
    limits = c(0, 850), 
    breaks = seq(0, 800, by = 200)
  ) +
  scale_color_manual(values = c(colorspace::darken("#00de6f", .4), "#00de6f")) +
  scale_linetype_manual(values = c("solid", 32)) +
  theme_lucile +
  labs(
    x = "Time (weeks)", 
    y = "&#35; of recovered&nbsp;&nbsp;*R*", 
    tag = expression(paste("(", italic("f"), ")"))
  )


## titles
plot_title <- 
  ggplot(tibble(x = 1, y = 1), aes(x, y)) + 
  coord_cartesian(clip = "off") +
  theme_void()

title_1 <- plot_title + 
  geom_text(aes(label = "Communal nursery"), 
            family = "Times New Roman", size = 10, fontface = "bold")
  
title_2 <- plot_title + 
  geom_text(aes(label = "Baseline"), 
            family = "Times New Roman", size = 10, fontface = "bold")

## FULL PANEL
title_1 / (plot_a + plot_b + plot_c) / plot_spacer() / title_2 / (plot_d + plot_e + plot_f) +
  plot_layout(heights = c(.15, 1, .1, .15, 1))

ggsave(here::here("figures", "fig_4_wide.pdf"), 
       width = 18, height = 9, device = cairo_pdf)
```

***
  
<details><summary>Session Info</summary>
  
```{r sessionInfo}
## DO NOT REMOVE!
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
  







