---
title: "IBM Den: Figure 1" 
date: "`r Sys.Date()`"
output: 
    distill::distill_article:
        highlight: kate
        code_folding: true  
        toc: true            
        toc_depth: 2         
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, 
                      retina = 1, dev = "ragg_png")
```


# Setup

```{r packages}
library(tidyverse)
library(ragg)
library(colorspace)
```


# Data

```{r data-prep}
output <- 
  readr::read_csv(
    here::here("data", "YBC_Continuous_Breeding continuous_breeding-table.csv"), 
    skip = 6
  ) %>% 
  janitor::clean_names() %>% 
  mutate(
    transmission = if_else(frequency_transmission == TRUE, "Frequency", "Density"),
    ext = if_else(ext == "extinct", 1, 0)
  ) %>% 
  arrange(run_number) %>% 
  as.data.frame()

gridim <- aggregate(output[,"ext"], list(rnot = output$rnot, age =   output[,"immunity_barrier"]), mean)
colnames(gridim) = c("Basic reproduction number R0", "Between-group contact", "Epidemic fade-out probability")

gridim[which(gridim$`Between-group contact` == 52), "Between-group contact"]<-"Communal nursery"
gridim[which(gridim$`Between-group contact` == 1), "Between-group contact"]<-"Baseline" 
```

# Figure

```{r plot, fig.width=8, fig.height=5}
theme_lucile <-
  theme_classic(base_size = 16, base_family = "Bitter") +
  theme(axis.title.x = element_text(size = 16, margin = margin(t = 15)),
        axis.title.y = element_text(size = 16, margin = margin(r = 15)),
        axis.line = element_line(colour = 'black', size = .8),
        axis.ticks = element_line(size = .8), 
        axis.ticks.length = unit(.3, "cm"),
        legend.position = c(.7, .85),
        legend.title = element_text(size = 16, face = "bold"),
        legend.text = element_text(size = 14),
        legend.key.width = unit(3, "lines"),
        legend.key.height = unit(1.3, "lines"),
        plot.margin = margin(10, 5, 5, 5))

ggplot(gridim, 
  aes(`Basic reproduction number R0`, 
      `Epidemic fade-out probability`, 
       color = `Between-group contact`,
       shape = `Between-group contact`)) + 
  geom_line(size = 1.5, alpha = .7) + 
  geom_point(size = 2.8, stroke = 1.7, fill = "white") +
  geom_point(size = 2.8, stroke = 1.7) +
  coord_cartesian(clip = "off") +
  scale_x_continuous(breaks = c(1, 2, 5, 10, 20)) +
  scale_y_continuous(limits = c(.48, 1), expand = c(0, 0)) +
  scale_color_manual(values = c("#7d408a", "#eb6f6c"), 
                     breaks = c("Communal nursery", "Baseline")) +
  scale_shape_manual(values = c(16, 21), 
                     breaks = c("Communal nursery", "Baseline"))+
  labs(x = expression("Basic reproduction number R"[0]),
       y = "Epidemic fade-out probability") +
  theme_lucile +
  theme(legend.background = element_rect(fill = "transparent", color = "transparent"))

ggsave(here::here("figures", "fig_1_abstract.pdf"), width = 7, height = 4, device = cairo_pdf)
```

***

<details><summary>Session Info</summary>

```{r sessionInfo}
## DO NOT REMOVE!
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
