---
title: "IBM Den: Figure 5" 
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    highlight: kate
    code_folding: true 
    toc: true            
    toc_depth: 2         
editor_options: 
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, 
                      retina = 1, dev = "ragg_png")
```


# Setup

```{r packages}
library(tidyverse)
library(ggtext)
library(colorspace)
library(patchwork)
library(systemfonts)
```


# Data

```{r new-data}
results_all <- 
  readr::read_csv(
    here::here("data", "YBC_Continuous_Breeding_20210422_agerepro single_run_continuous_breeding-table_agerepro.csv"), 
    skip = 6
  ) %>% 
  janitor::clean_names() %>% 
  #rename(protected = nonprot) %>% 
  mutate(type = if_else(immunity_barrier == 1, "baseline", "YBC")) %>% 
  dplyr::select(step:locked, protected, type) %>% 
  mutate(
    rest = sealed - protected - locked,
    open = 20 - sealed
  ) %>% 
  filter(step > 0)

results <- filter(results_all , type == "YBC")
resultsNO <- filter(results_all , type == "baseline")

vec <- matrix(0, nrow = (length(results$rest)*4), ncol = 2)

r <- 1

for(i in 1:length(results$rest)) {
  vec[r:(r+3),1] <- rep(i,4)
  vec[r:(r+3),2] <- t(results[i,c("locked", "protected", "rest", "open")])
  r <- r + 4
}  


vecbis_a <- NULL

for(i in 1:200){
  vec_a <- rep(1, results[i,"sealed"])
  vec_a2 <- rep(2, results[i,"protected"])
  vec_a3 <- rep(3, (results[i,"open"] + results[i,"rest"]))
  
  
  bound <- c(vec_a, vec_a2,vec_a3)
  vecbis_a <- rbind(vecbis_a, cbind(rep(i,length(bound)), bound))
}  


df_vecbis_a <- as_tibble(vecbis_a) %>% 
  mutate(bound = factor(bound, levels = c("3", "2", "1")))



resultsNO$rest <- resultsNO$sealed - resultsNO$protected - resultsNO$locked
resultsNO$open <- 20 - resultsNO$sealed
vec <- matrix(0, nrow = (length(resultsNO$rest)*4), ncol = 2)

r <- 1
for(i in 1:length(resultsNO$rest)){
  vec[r:(r+3),1] <- rep(i,4)
  vec[r:(r+3),2] <- t(resultsNO[i,c("locked", "protected", "rest", "open")])
  r <- r + 4
}

vecbis_b <- NULL

for(i in 1:200){
  vec_b <- rep(1, resultsNO[i,"sealed"])
  vec_b2 <- rep(2, resultsNO[i,"protected"])
  vec_b3 <- rep(3, (resultsNO[i,"open"] + resultsNO[i,"rest"]))

  bound <- c(vec_b, vec_b2,vec_b3)
  vecbis_b <- rbind(vecbis_b, cbind(rep(i,length(bound)), bound))
}


df_vecbis_b <- as_tibble(vecbis_b) %>%
  mutate(bound = factor(bound, levels = c("3", "2", "1")))

```

# Figure

```{r plot, fig.width=10, fig.height=13.5}
theme_custom <-
  theme_classic(base_size = 18, base_family = "Times New Roman") +
  theme(axis.title.x = element_text(size = 19, margin = margin(t = 15)),
        axis.title.y = element_text(size = 19, margin = margin(r = 8)),
        axis.text = element_text(size = 16),
        axis.ticks = element_line(size = .8), 
        axis.ticks.length = unit(.2, "cm"),
        axis.line = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA, size = .8),
        plot.title = element_text(face = "bold", size = 24, margin = margin(0, 0, 10, 0), hjust = .5),
        plot.tag = element_text(face = "italic", size = 24),
        legend.position = "none")

a <- 
  ggplot(tibble(x = 1:10, y = 1:10),
         aes(x, y)) +
    labs(tag = expression(paste("(", italic("a"), ")"))) +
    theme_void() +
    theme(plot.tag = element_text(family = "Times New Roman",
                                  face = "italic", size = 24),)
    

labs_b <-
  tibble(
    x = c(73, 95, 167),
    y = c(.23, .7, .5),
    label = c("Groups consisting of recovered<br>adults and infected juveniles<br>**(sealed)**",
              "Groups consisting of<br>susceptible and/or infected adults<br>**(open)**",
              "Groups consisting of recovered<br>adults and susceptible juveniles<br>**(sealed)**")
  )

colors <- c("#83c2ca", "#ebce77", "#b96777")

b <- 
  ggplot(df_vecbis_a, aes(V1, ..count..)) +
    geom_density(aes(fill = bound),
                 position = "fill", color = NA) +
    geom_richtext(data = labs_b, 
                  aes(x, y, label = label),
                  family = "Times New Roman",
                  size = 4.8,
                  fill = NA, 
                  label.color = NA) +
    coord_cartesian(clip = "off") +
    scale_x_continuous(expand = c(0, 0), 
                       limits = c(0, 200)) +
    scale_y_continuous(expand = c(0, 0), 
                       limits = c(0, 1)) +
    scale_fill_manual(values = colors) +
    labs(x = NULL, 
         y = "Proportion of groups", 
         title = "Communal nursery", 
         tag = expression(paste("(", italic("b"), ")"))) +
    theme_custom

labs_c <-
  tibble(
    x = c(100, 100, 100),
    y = c(.27, .57, .83),
    label = c("Groups of recovered adults<br>and infected juveniles<br>**(open)**",
              "Groups of susceptible and/or infected adults **(open)**",
              "Groups of recovered adults<br>and susceptible juveniles<br>**(open)**")
  )

colors_pale <- c(lighten("#83c2ca", .4), "#ebce77", lighten("#b96777", .4))

c <- 
  ggplot(df_vecbis_b, aes(V1, ..count.., fill = bound)) +
    geom_density(position = "fill", color = NA) +
    geom_richtext(data = labs_c, 
                  aes(x, y, label = label),
                  family = "Times New Roman",
                  size = 4.8,
                  fill = NA, 
                  label.color = NA) +
    coord_cartesian(clip = "off") +
    scale_x_continuous(expand = c(0, 0), 
                       limits = c(0, 200)) +
    scale_y_continuous(expand = c(0, 0), 
                       limits = c(0, 1)) +
    scale_fill_manual(values = colors_pale) +
    labs(x = "Weeks", 
         y = "Proportion of groups", 
         title = "Baseline scenario", 
         tag = expression(paste("(", italic("c"), ")"))) +
    theme_custom


a / b / c

ggsave(here::here("figures", "fig_5.pdf"), width = 10, height = 13.5, device = cairo_pdf)  
```

***
  
<details><summary>Session Info</summary>
  
```{r sessionInfo}
## DO NOT REMOVE!
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
  
